### ISSUE TITLE
Feedback on kvbench results : why is with fsync so slow ? 

### ISSUE THREAD

**Issue by chmike** [nutsdb/nutsdb#101]
https://github.com/smallnest/kvbench

Looking at the benchmark, the performance of NutsDB with fsync seam horrible. 
Are they doing something wrong or is this normal ?

**Comment by xujiajun** [comment]
@chmike hi，I will reply to you after I test this program.

**Comment by xujiajun** [comment]
@chmike When calling sync, each entry write will call sync, so it is very slow, but it ensures that data will not be lost.
