### ISSUE TITLE
db.buildIndexes error: when build activeDataIndex readAt err:  crc error

### ISSUE THREAD

**Issue by icecolbeveridge** [nutsdb/nutsdb#141]
**Describe the bug**

When initialising the database, nutsdb generates an error:

`db.buildIndexes error: when build activeDataIndex readAt err:  crc error`

**To Reproduce**

My db setup code is below:

```
type Store struct {
	nuts *nutsdb.DB
	log  *logging.Info
}

func NewStore() *Store {
	D := Store{}

	var err error

	opt := nutsdb.DefaultOptions
	opt.Dir = "data/"
	D.nuts, err = nutsdb.Open(opt)
	if err != nil {
		panic(err)
	}
	D.Set("cd", []byte("_"), []byte("")) // create a bucket
	return &D
}
```

The error occurred with a db that has been working fine for some months, but also occurs with a new one. It first manifested when using goconvey to run tests concurrently. I'm running go1.17.2 linux/amd64 on Ubuntu 20.04.

**Expected behavior**

I expected the database to not return an error.

**What actually happens**

The error 
`db.buildIndexes error: when build activeDataIndex readAt err:  crc error`
is returned.

**please complete the following information :**
 - OS: Ubuntu 20.04
 - NutsDB Version 0.8.0 (but the error first manifested on 0.6.0)

**Additional context**
Only that I'm a fan of nutsdb -- it was the first golang db I tried, and it slotted straight into the project without difficulty. I appreciate your work :-)

**Comment by xujiajun** [comment]
@icecolbeveridge First of all, thank you for using nutsdb. The initialization code you gave cannot reproduce this error. Can you provide a simulated data file to ensure that this error is reproduced, or execute the written code, so that the initialization file can be read?

**Comment by icecolbeveridge** [comment]
Sure -- here is a zip:
[cd.zip](https://github.com/nutsdb/nutsdb/files/8470608/cd.zip)

(I'm quite prepared to believe I'm doing something wrong, but I can't figure out what it is.)

**Comment by xujiajun** [comment]
@icecolbeveridge 

Sorry for the late reply, I tested it with your data, and what you said does happen: panic: db.buildIndexes error: when build activeDataIndex readAt err: crc error

I will explain this crc. This is the checksum, which is used to check whether the data is consistent.

I found that reading the second entry, the two crcs are different,
They are:
crc 2313456195 (represents crc calculated by bucket, key, value)
e.crc 3311061663 (indicated in entry)

It means that your data has been changed.  Did you do anything special?

This is the crc algorithm, which is related to bucket, key, and value:

https://github.com/nutsdb/nutsdb/blob/master/entry.go#L112

```
// GetCrc returns the crc at given buf slice.
func (e *Entry) GetCrc(buf []byte) uint32 {
crc := crc32.ChecksumIEEE(buf[4:])
crc = crc32.Update(crc, crc32.IEEETable, e.Meta.Bucket)
crc = crc32.Update(crc, crc32.IEEETable, e.Key)
crc = crc32.Update(crc, crc32.IEEETable, e.Value)

return crc
}
```

**Comment by icecolbeveridge** [comment]
Looking at #63, my hypothesis is that it's a problem with goconvey running tests concurrently -- the tests in my database module start up an instance of nutsdb, and the tests in a different module start another. Is that a plausible cause?

**Comment by xujiajun** [comment]
@icecolbeveridge Yes, when you create different instances and write the same file concurrently, data tampering will occur. It is recommended to build different db instances and create different directories. The concurrent test is also to test the same db instance.

**Comment by icecolbeveridge** [comment]
OK, thank you. I'll mark this as closed.
