### ISSUE TITLE
不是很理解，这段代码逻辑

### ISSUE THREAD

**Issue by ztyandjw** [nutsdb/nutsdb#154]
想请教下面2个问题：

1、通过key，针对于b+树索引出文件路径与读取偏移量，我不理解为什么还要对TXID的索引树进行查询
2、不理解对trasaction id为什么要做个索引树？如果要做，不用hash用bptree是什么考虑

万分感谢！

```
func (tx *Tx) getByHintBPTSparseIdxInMem(key []byte) (e *Entry, err error) {
	// Read in memory.
	r, err := tx.db.ActiveBPTreeIdx.Find(key)
	if err == nil && r != nil {
		if _, err := tx.db.ActiveCommittedTxIdsIdx.Find([]byte(strconv2.Int64ToStr(int64(r.H.Meta.TxID)))); err == nil {
			path := tx.db.getDataPath(r.H.FileID)
			df, err := NewDataFile(path, tx.db.opt.SegmentSize, tx.db.opt.RWMode)
			if err != nil {
				return nil, err
			}
			defer df.rwManager.Close()
			result,e := df.ReadAt(int(r.H.DataPos))
			return result, e
		}

		return nil, ErrNotFoundKey
	}

	return nil, nil
}
```

**Comment by xujiajun** [comment]
@ztyandjw hello，
我回答下你的问题。
> 1、通过key，针对于b+树索引出文件路径与读取偏移量，我不理解为什么还要对TXID的索引树进行查询

因为b+树读出来未必是事务提交的，所以需要ActiveCommittedTxIdsIdx（已经提交的事务id）确认下

> 2、不理解对trasaction id为什么要做个索引树？如果要做，不用hash用bptree是什么考虑

这个模式的背景是设计节约内存的方式，hash虽然可以实现，但是他需要把所有key放内存中进行索引，那么如果有成千上万的甚至上亿的key呢，都要要放内存，务必会很耗内存，而bptree非常适合磁盘检索，可以做到少量索引（占少量内存）完成检索。

**Comment by ztyandjw** [comment]
> @ztyandjw hello， 我回答下你的问题。
> 
> > 1、通过key，针对于b+树索引出文件路径与读取偏移量，我不理解为什么还要对TXID的索引树进行查询
> 
> 因为b+树读出来未必是事务提交的，所以需要ActiveCommittedTxIdsIdx（已经提交的事务id）确认下
> 
> > 2、不理解对trasaction id为什么要做个索引树？如果要做，不用hash用bptree是什么考虑
> 
> 这个模式的背景是设计节约内存的方式，hash虽然可以实现，但是他需要把所有key放内存中进行索引，那么如果有成千上万的甚至上亿的key呢，都要要放内存，务必会很耗内存，而bptree非常适合磁盘检索，可以做到少量索引（占少量内存）完成检索。另外trasaction id做索引原因就是问题的1的答案

@xujiajun 
非常感谢，  针对于以下方法，获取文件路径对应的内存数据结构，也是b+树，但是这棵树，只会在方法buildTxIDRootIdx
生成，并且只会插入一值 《rootAddress》，这个为什么也要构建一颗b+树呢？


```
func (db *DB) getBPTRootTxIDPath(fID int64) string {
	return db.getBPTDir() + "/txid/" + strconv2.Int64ToStr(fID) + BPTRootTxIDIndexSuffix
}
```

**Comment by xujiajun** [comment]
> > @ztyandjw hello， 我回答下你的问题。
> > > 1、通过key，针对于b+树索引出文件路径与读取偏移量，我不理解为什么还要对TXID的索引树进行查询
> > 
> > 
> > 因为b+树读出来未必是事务提交的，所以需要ActiveCommittedTxIdsIdx（已经提交的事务id）确认下
> > > 2、不理解对trasaction id为什么要做个索引树？如果要做，不用hash用bptree是什么考虑
> > 
> > 
> > 这个模式的背景是设计节约内存的方式，hash虽然可以实现，但是他需要把所有key放内存中进行索引，那么如果有成千上万的甚至上亿的key呢，都要要放内存，务必会很耗内存，而bptree非常适合磁盘检索，可以做到少量索引（占少量内存）完成检索。另外trasaction id做索引原因就是问题的1的答案
> 
> @xujiajun
> 
> 感谢回复， 针对于以下方法，获取文件路径对应的数据结构，也是b+树。 但是这棵树，只会在方法buildTxIDRootIdx 生成，并且全树只会插入一次，就是生成的时候插入当前txid树的 rootaddress，就一个值为什么也要构建b+树？
> 
> 谢谢！
> 
> ```
> func (db *DB) getBPTRootTxIDPath(fID int64) string {
> 	return db.getBPTDir() + "/txid/" + strconv2.Int64ToStr(fID) + BPTRootTxIDIndexSuffix
> }
> ```

一次事务只会执行一次buildTxIDRootIdx，但是一次事务可能会有n棵b+树产生，所以这个也得有对应的索引维护rootaddress和b+树的关系。

**Comment by ztyandjw** [comment]
感谢回复 closed
