### ISSUE TITLE
代码中的一个小漏洞。

### ISSUE THREAD

**Issue by andrewhzy** [nutsdb/nutsdb#177]
如下代码如果传入的count为 -1<<63时，-count的取值不正确，需做validation。
![image](https://user-images.githubusercontent.com/71499897/177176408-861dfea2-dcc8-4a14-97f9-10a6047ac8f7.png)

**Comment by xujiajun** [comment]
@andrewhzy 谢谢指出问题

**Comment by xujiajun** [comment]
说明下：应该是count 如果是最小值math.MinInt64，-count还是math.MinInt64本身，本身不会报错，就是没有达到预期。可能提示不能使用math.MinInt64会比较好，或者还有其他方案看下。
