### ISSUE TITLE
内存模式下没有PrefixScan

### ISSUE THREAD

**Issue by ttttmr** [nutsdb/nutsdb#188]
**Describe the bug**
内存模式下没有PrefixScan的功能，似乎也少了其他的一些功能

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
```
opts := inmemory.DefaultOptions
db, err := inmemory.Open(opts)

db.PrefixScan()
```

**Expected behavior**
内存模式下有完整功能
ps: 文档也没写内存模式有什么功能缺失

**What actually happens**
A clear and concise description of what actually happens.

**Screenshots**

**please complete the following information :**
 - NutsDB Version v0.9.0

**Additional context**

**Comment by xujiajun** [comment]
是的 内存模式 有一些功能缺失，可以加上去。

**Comment by xujiajun** [comment]
closed .see detail :https://github.com/nutsdb/nutsdb/pull/211
