### ISSUE TITLE
[新人提问] log 文件压缩以及是否能当作 redis 用？

### ISSUE THREAD

**Issue by zyxxoo** [nutsdb/nutsdb#189]
hi, 我今天大概简单的学习了一下 nutsdb 的源代码，有些疑问（可能没看到）想请教下
1. 看代码我的理解是磁盘文件就是 log 文件，请问如何减少log文件的大小呢（暂时没有在源代码中发现压缩逻辑）?
2. 目前看都是内存索引，所以是不是可以将 nutsdb 当作redis来用, 只不过所有的数据都写入了 log 文件，启动的时候重新读log,构建索引

**Comment by xujiajun** [comment]
有问题再提，我关闭了这个issue
