### ISSUE TITLE
重做Benchmark

### ISSUE THREAD

**Issue by xbchaos** [nutsdb/nutsdb#217]
最近在找寻类似的组件，一直在作选型对比。昨天刚看到BadgerDB，今天看到了nutsdb。从介绍来看nutsdb确实有很多独特亮点（比如支持list、set和sorted set）。

我注意到README里有和BadgerDB的性能对比数据，但这份数据其实是2019年3月份的，作者方便有空的时候更新一下最新版本的性能对比数据吗？感谢！

**Comment by elliotchenzichang** [comment]
hi～之前有考虑过单独弄一个benchmark相关的项目，项目已经建好了，不过一直没有抽出空来写。我们这几个版本也有做性能优化，最近也会发一版新的，发新版之后我们再做一次两者最新版的性能比较～
