### ISSUE TITLE
[Feature] realize auto Merge

### ISSUE THREAD

**Issue by elliotchenzichang** [nutsdb/nutsdb#246]
Now users can only use the Merge method to recycle useless data to save space. But in most scenarios, users don't know when to recycle and when to call the Merge method. Here it is proposed to implement an automatic recycling mechanism, to implement some automatic recycling mechanisms, such as when the useless data reaches 1/3 of the total data? ? This is a relatively large feature that involves many changes, as well as the measurement and research of the triggering criteria of the recovery mechanism. How to find a standard with a theoretical basis is also a relatively large task. But even so, some things can still be realized in advance, such as counting useless data and total data in the current db. Establish a statistical mechanism. My idea is to implement this mechanism according to the following steps.

1. Establish statistical data standards, which can update the total data and invalid data in the db in real time.
2. Conduct research on recycling standards and find some theoretical basis.
3. Meet this recycling standard.

现在用户只能通过出发Merge方法回收无用的数据，达到节省空间的效果。但是在大部分场景中用户也不知道什么时候该回收，什么时候该调用Merge方法。在这里提议实现一个自动回收的机制，实现一些自动回收的机制，比如当无用数据达到总数据的1/3？？这是一个相对较大的feature，涉及的改动会比较多，以及对回收机制触发标准的衡量以及研究。如何找到一个有理论依据的标准，这也是一个比较大的工作。但是即便如此，依旧有一些东西是可以提前实现的，比如统计当前db中无用数据以及总数据。建立一个统计机制。我的想法是依照以下步骤实现这个机制。

- [ ] #297 @Schofi  p1
- [ ] #292 @xuyukeviki p1
- [ ] #296  @andrewhzy p0
- [ ] #298 @andrewhzy p0
- [ ] #299 @wangxuanni p1
- [ ] #300 @Gomaz-YueYue p1

**Comment by elliotchenzichang** [comment]
1.  Pending：自动Merge带有TTL的Key （并行处理）
2. 统计指标精细到单个文件（有效空间比例 + 有效的Key比例）
3. 开放这些操作方式，作为配置给用户使用

**Comment by wangxuanni** [comment]
认领[自动删除过期的key](https://github.com/nutsdb/nutsdb/issues/292)和[实现Merge单个文件操作](https://github.com/nutsdb/nutsdb/issues/299)

**Comment by ShawnHXH** [comment]
assign me #292

**Comment by elliotchenzichang** [comment]
> assign me #292

done

**Comment by Schofi** [comment]
assign me https://github.com/nutsdb/nutsdb/issues/297

**Comment by andrewhzy** [comment]
assign me #298

**Comment by elliotchenzichang** [comment]
> assign me #298

done

**Comment by elliotchenzichang** [comment]
> assign me #296

done
