### ISSUE TITLE
Caching strategy

### ISSUE THREAD

**Issue by DannyZB** [nutsdb/nutsdb#249]
In a project I am working on NutsDB will act as a replacement for MySQL innodb for some scenarios.

What I couldnt find in this project is the caching and eviction strategies, if such exist. Equivalent to the innodb buffer pool.

Is the preferred method memory mapping and you only depend on the filesystem cache?

If the same key and bucket are repeatedly requested do they end up in an internal cache, or repeatedly fetched from the filesystem?

Also, how are filesystem blocks handled? Are they loaded in whole into the memory or you just open the ranges immediately needed?

Would be useful to know the preferred way to handle this if there is one. Otherwise putting a memory cache on top of NutsDB is probably a good idea for a large project.

**Comment by xujiajun** [comment]
Hi, NutsDB has 3 modes: HintKeyValAndRAMIdxMode, HintKeyAndRAMIdxMode and HintBPTSparseIdxMode. HintKeyValAndRAMIdxMode indicates the ram index (key and value) mode, HintKeyAndRAMIdxMode indicates the ram index (only key) mode, and HintBPTSparseIdxMode indicates the b+ tree sparse index mode.
The mode of HintBPTSparseIdxMode needs the caching strategy you mentioned.

**Comment by DannyZB** [comment]
I would add a section explaining those modes in short.
To me it's clear but some other coders I know had issues following the explanation.

This is a great project, the documentation could use some additions though.

I'll start using this in some big projects so might have some input down the road.

**Comment by elliotchenzichang** [comment]
Hi, @DannyZB, I am one of the maintainers of this project. I prefer to build a cache strategy that saves the frequently access entry in memory in Nutsdb.
