### ISSUE TITLE
LTrim无法清空列表

### ISSUE THREAD

**Issue by icpd** [nutsdb/nutsdb#253]
**Describe the bug**
在 Redis 中当 start > stop 时，list会被清空。而 nustdb 则返回错误 `start or end error`。不知道可否实现清空列表方法

**please complete the following information :**
 - NutsDB Version v0.11.0

**Comment by xujiajun** [comment]
NutsDB 设计的时候就是这样的。start > stop 个人感觉不是很好，不够语义化，如果要清空 可以重新设计一个清空列表的api比较好。
