### ISSUE TITLE
调用Delete删除key无效

### ISSUE THREAD

**Issue by icpd** [nutsdb/nutsdb#254]
调用 `Delete` 删除 list key 后，执行 lsize 和 lrange 依然可以拿到值

nutsdb version：v0.11.1
entryIdxMode：HintKeyAndRAMIdxMode

**Comment by xujiajun** [comment]
你说的是tx.Delete方法吧 在nutsdb中和 list没有关系

**Comment by icpd** [comment]
那怎么删除整个list呢

**Comment by xujiajun** [comment]
比如可以先调用LSize  知道大小size ，然后用LTrim(bucket, key, 0, size-1)
