### ISSUE TITLE
大量插入数据

### ISSUE THREAD

**Issue by CaiZongLin** [nutsdb/nutsdb#257]
请问要如何在以ZAdd 的情况下插入大量数据而不要耗费太多时间？目前遇到情况是会需要写入大量KV资料，约有五百万笔数据，因为档案是在csv内，目前是会先读csv后用for去跑data后逐笔写入，

**Comment by xujiajun** [comment]
@CaiZongLin 使用批量的插入 参考 https://github.com/nutsdb/nutsdb/blob/master/examples/batch/put/main.go

**Comment by azhsmesos** [comment]
我们是否可以直接提供一个读取csv文件的接口

**Comment by CaiZongLin** [comment]
@xujiajun 您好，感謝您抽空回覆。
請問您貼的連結也是用For迴圈逐筆寫入，這樣與我寫的這個方式有什麼區別呢？謝謝您
![image](https://user-images.githubusercontent.com/99956021/207524626-c98a4d23-cd35-4f11-98a1-7555b0ee86b8.png)

**Comment by xujiajun** [comment]
> @CaiZongLin 使用批量的插入 参考 https://github.com/nutsdb/nutsdb/blob/master/examples/batch/put/main.go

对的

**Comment by xujiajun** [comment]
先关闭了，有问题再提issue吧。
