### ISSUE TITLE
go.mod is redirecting away from this project to a fork

### ISSUE THREAD

**Issue by steowens** [nutsdb/nutsdb#261]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior(Be specific!): 
1.  Go to the command line and type the following and observe
    
    go get github.com/nutsdb/nutsdb
    go: github.com/nutsdb/nutsdb@v0.11.1: parsing go.mod:
        module declares its path as: github.com/xujiajun/nutsdb
                but was required as: github.com/nutsdb/nutsdb

**Expected behavior**
I did not expect to see such an unexpected result.  I would have expected the module links to the correct github organization.

**What actually happens**
A clear and concise description of what actually happens.
See above.

**Comment by elliotchenzichang** [comment]
Actually, we use this one  **github.com/xujiajun/nutsdb** in our code, so maybe we need to change it.  @xujiajun

**Comment by elliotchenzichang** [comment]
#281
