### ISSUE TITLE
panic: runtime error: slice bounds out of range [:1701013878] with capacity 166033783

### ISSUE THREAD

**Issue by mindon** [nutsdb/nutsdb#262]
https://github.com/mindon/nutsdb/blob/master/entry.go line 124
```golang
func (e *Entry) ParsePayload(data []byte) error {
	if e.Meta == nil || (e.Meta.BucketSize+e.Meta.KeySize+e.Meta.ValueSize != uint32(len(data))) {
		return errors.New("data validation fail")
	}
```

这里的 3 个 uint32 相加和一个 uint32 对比，可能会有问题。

碰到 1701013878 + 131073 + 2759856128 = 4,461,001,079 超过了 uint32 最大值 4,294,967,295 导致 后面的代码数组越界 panic

库读取失败。

**Comment by elliotchenzichang** [comment]
@mindon 感谢提醒，我看下怎么改改～

**Comment by lyr-2000** [comment]
改成 uint64 吗？

**Comment by elliotchenzichang** [comment]
这个issue之前已经修复了。我cliose一下。
