### ISSUE TITLE
serialization of BinaryNode in BPTree

### ISSUE THREAD

**Issue by ShawnHXH** [nutsdb/nutsdb#270]
在 `bptree.go` 中，`BPTree.ToBinary:L217` 方法的目的应该是以二进制形式序列化一个节点。

由于 BPTree 在创建时，其 `enablePosMap=False`，所以 `BPTree.ToBinary:L217` 方法会进入下列条件处理：

```go
//  Line 221
	for i = 0; i < n.KeysNum; i++ {
		if t.enabledKeyPosMap {
			// ...
		} else {
			key, _ := strconv2.StrToInt64(string(n.Keys[i]))
			keys[i] = key
		}
	}
```

其中，`strconv2.StrToInt64` 函数只会把字面量为整形数字的字符串转换成 Int64 类型，而对于包含有字母的 Key 来说，它们都会被转换为 0，比如：

```go
n.Keys = ["key1", "key2", "key3", ...]
strconv2.StrToInt64(n.Keys) = [0, 0, 0, ...]
```

最后 `BPTree.ToBinary:L217` 方法中创建的 `BinaryNode` 对象，其 Keys 字段会为一个全 0 的切片。而且该节点通过 `BPTree.WriteNodes` 方法持久化，使用 `bptree.go:ReadNode` 读出后，仍然为一个全 0 的字段。

那么这样的序列化存在什么特殊意义吗？还是完全不需要序列化 Keys ？

如果是完全不需要保存 Keys 的话，那么在 `tx_bptree.go` 中，`tx.FindLeafOnDisk:L1012` 方法里：

```go
func (tx *Tx) FindLeafOnDisk(fID int64, rootOff int64, key, newKey []byte) (bn *BinaryNode, err error) {
	var i uint16
	var curr *BinaryNode

	filepath := tx.db.getBPTPath(fID)
	curr, err = ReadNode(filepath, rootOff)
	// ...

	for curr.IsLeaf != 1 {
		i = 0
		for i < curr.KeysNum {
			df, err := tx.db.fm.getDataFile(tx.db.getDataPath(fID), tx.db.opt.SegmentSize)
			// ...

			item, err := df.ReadAt(int(curr.Keys[i]))
			// ...
		}
		address := curr.Pointers[i]
		curr, err = ReadNode(filepath, address)
	}
	return curr, nil
}
```

L1030 的 `df.ReadAt(int(curr.Keys[i]))` 中，不就会一直 `df.ReadAt(0)` 吗？

不是很懂这里的设计。

**Comment by xujiajun** [comment]
@ShawnHXH 

> 其中，strconv2.StrToInt64 函数只会把字面量为整形数字的字符串转换成 Int64 类型，而对于包含有字母的 Key 来说，它们都会被转换为 0，比如：

> n.Keys = ["key1", "key2", "key3", ...]
> strconv2.StrToInt64(n.Keys) = [0, 0, 0, ...]

你说的这个情况不存在，因为这边二进制存的key是都是数字，比如事务id、offset之之类的。

**Comment by ShawnHXH** [comment]
好的，谢谢解答
