### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by weiwenhao** [nutsdb/nutsdb#273]
**Describe the bug**

panic: runtime error: makeslice: len out of range
goroutine 1 [running]:
[github.com/xujiajun/nutsdb.(*DataFile).ReadAt](http://github.com/xujiajun/nutsdb.(*DataFile).ReadAt)(0x845bee10, 0x0)
        /root/go/pkg/mod/[github.com/xujiajun/nutsdb@v0.11.1/datafile.go:81](http://github.com/xujiajun/nutsdb@v0.11.1/datafile.go:81) +0x1c4
[github.com/xujiajun/nutsdb.(*DB).getActiveFileWriteOff(0x8472a640)](http://github.com/xujiajun/nutsdb.(*DB).getActiveFileWriteOff(0x8472a640))
        /root/go/pkg/mod/[github.com/xujiajun/nutsdb@v0.11.1/db.go:511](http://github.com/xujiajun/nutsdb@v0.11.1/db.go:511) +0x78
[github.com/xujiajun/nutsdb.(*DB).buildIndexes(0x8472a640)](http://github.com/xujiajun/nutsdb.(*DB).buildIndexes(0x8472a640))
        /root/go/pkg/mod/[github.com/xujiajun/nutsdb@v0.11.1/db.go:962](http://github.com/xujiajun/nutsdb@v0.11.1/db.go:962) +0xb8
[github.com/xujiajun/nutsdb.open](http://github.com/xujiajun/nutsdb.open)({{0x847cd740, 0x2e}, 0x0, 0x0, 0x200000, 0x1, 0x1, 0x0, 0x0, 0x0})
        /root/go/pkg/mod/[github.com/xujiajun/nutsdb@v0.11.1/db.go:240](http://github.com/xujiajun/nutsdb@v0.11.1/db.go:240) +0x584
[github.com/xujiajun/nutsdb.Open](http://github.com/xujiajun/nutsdb.Open)({{0x0, 0x0}, 0x0, 0x0, 0x10000000, 0x1, 0x1, 0x0, 0x0, 0x0}, ...)
        /root/go/pkg/mod/[github.com/xujiajun/nutsdb@v0.11.1/db.go:253](http://github.com/xujiajun/nutsdb@v0.11.1/db.go:253) +0xb8
iaas/utils/localdb.Init({0x847cd740, 0x2e})
        /app/utils/localdb/localdb.go:15 +0xc0
iaas/client/cmd.glob..func4(0xb6ab2d88, {0x84a9f6c0, 0x0, 0x8})
        /app/client/cmd/root.go:102 +0x9d8
[github.com/spf13/cobra.(*Command).execute](http://github.com/spf13/cobra.(*Command).execute)(0xb6ab2d88, {0x84438058, 0x8, 0x9})
        /root/go/pkg/mod/[github.com/spf13/cobra@v1.0.0/command.go:846](http://github.com/spf13/cobra@v1.0.0/command.go:846) +0x6d4
[github.com/spf13/cobra.(*Command).ExecuteC(0xb6ab2d88)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xb6ab2d88))
        /root/go/pkg/mod/[github.com/spf13/cobra@v1.0.0/command.go:950](http://github.com/spf13/cobra@v1.0.0/command.go:950) +0x44c
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
        /root/go/pkg/mod/[github.com/spf13/cobra@v1.0.0/command.go:887](http://github.com/spf13/cobra@v1.0.0/command.go:887)
iaas/client/cmd.Execute()
        /app/client/cmd/root.go:270 +0x24
main.main()
        /app/client/main.go:16 +0x14

**To Reproduce**
Steps to reproduce the behavior(Be specific!):

init code

```golang
// 建立链接的代码
db, err := nutsdb.Open(
		nutsdb.DefaultOptions,
		nutsdb.WithSegmentSize(2*nutsdb.MB),
		nutsdb.WithDir(dir), 
	)


// 写入代码
err := db.Update(func(tx *nutsdb.Tx) error {
		if err := tx.Put(DefaultBucket, []byte(key), value, ttl); err != nil {
			return err
		}
		return nil
	})
```

进程 A 通过上面的代码创建链接， 并写入 key/value （程序 A 运行中，未关闭链接）， 进程 B 再次创建链接时 panic

db 文件: 
-rw-r--r-- root     root      2097152 2023-01-10 18:08 0.dat

**please complete the following information :**
 - OS: Linux localhost 3.10.0 253 SMP PREEMPT Thu May 19 18:50:38 CST 2022 armv7l
 - NutsDB Version v0.11.1

**Comment by xujiajun** [comment]
@weiwenhao  多进程 打开同一个db，会有问题的。目前版本只支持单进程。后面支持的话，文件锁是个思路，看有没人来参与下。

**Comment by weiwenhao** [comment]
加文件锁即可，没有锁进程让我误以为能改支持多进程链接。
