### ISSUE TITLE
LIST "start or end error" after deleting the last item from list 

### ISSUE THREAD

**Issue by Defex** [nutsdb/nutsdb#280]
**Describe the bug**
It seems that `reading` the list breaks, after deleting the last item from it.

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
1.   Create a list and push one item
```
err = tx.RPush("userItemIds", []byte("user1"), []byte("item1"))
if err != nil {
	return fmt.Errorf("failed to push ids list: %v", err)
}
```
2.  Remove the item
```
_, err = tx.LRem("userItemIds", []byte("user1"), 0, []byte("item1"))
if err != nil {
	return err
}
```

3.  Retrieve the list
```
err := q.DB.View(func(tx *nutsdb.Tx) error {
data, err := tx.LRange("userItemIds", []byte("user1"), 0, -1)
if errors.Is(err, nutsdb.ErrBucket) || errors.Is(err, list.ErrListNotFound) {
	return nil
}

....

return nil
})
```

**Expected behavior**
The item is removed, retrieving the list throws "list.ErrListNotFound"

**What actually happens**
Retrieving the list throws: `start or end error`.

**please complete the following information :**
 - OS: [Ubuntu 22]
 - NutsDB Version [v0.11.1]

**Additional context**
The list can't be read after trying to delete the last item. it produces the same error ``start or end error`.

**Comment by ShawnHXH** [comment]
Sure there is a bug in it.

https://github.com/nutsdb/nutsdb/blob/751c6f115ea9ec2250e16df7b7b400b509ec13fc/ds/list/list.go#L175-L207

the `list.ErrListNotFound` error only can be triggered when the `key` in the `List` has expired.

However, the `start or end error` happens becasue `size, start, end = 0, 0, -1`, it leads to `if start > end` branch.

Thanks for reporting, I will fix it.
