### ISSUE TITLE
[讨论] 是否考虑去除Merge方法

### ISSUE THREAD

**Issue by elliotchenzichang** [nutsdb/nutsdb#284]
Merge是Bitcask论文中提出的方法，意在去除DB中的无效数据，做到类似GC的效果，作为一个开放出去的API会增加用户的理解成本和心智负担，提议去除掉Merge这个开放的API，转而由DB内部维护一套机制去做GC。

**Comment by xuyukeviki** [comment]
我有也有类似的想法，我觉得定时或者定量自动的进行merge操作可能会更加好一点

**Comment by elliotchenzichang** [comment]
可以提供给用户更多的选择，这个可以保留下来。

**Comment by xujiajun** [comment]
类似go语言，自动GC和手动GC 共存不矛盾。
