### ISSUE TITLE
搞个微信交流群吧（Get a WeChat communication group）

### ISSUE THREAD

**Issue by dulumao** [nutsdb/nutsdb#29]
RT

**Comment by xujiajun** [comment]
@dulumao 你好 当你的留言聚齐至少10个赞时，我再开通微信群，你看好吧？ 不然我觉得如果人不多意义不大。

点赞的人 可以 点击  右边的 `Subscribe` 按钮，可以及时收到微信群开通的通知。

**Comment by xujiajun** [comment]
好的 我发现已经到 10个赞了，@dulumao 先加我的个人微信：xujiajun1234567 

我再建个群

**Comment by xujiajun** [comment]
![image](https://user-images.githubusercontent.com/6065007/58849354-99928200-86bc-11e9-9a37-5ad142527b65.png)

**Comment by chaseSpace** [comment]
支磁！！！

**Comment by leopku** [comment]
有没有大佬建个 TG 群？

**Comment by hemmmapart** [comment]
康康
