### ISSUE TITLE
[Feature] Automatically delete expired keys 自动删除过期的key

### ISSUE THREAD

**Issue by wangxuanni** [nutsdb/nutsdb#292]
At present, only when checking the key, check whether the key has expired and then delete it, that is, lazy deletion. A mechanism can be implemented to automatically clear expired data based on memory usage. The implementation method is: maintain a zset, the score is ttl, and the key is the original key. Use ZRangeByScore() to find out the keys that have expired so far and delete them.
This function provides support for the automatic merge function, because this function can count the effective proportion of keys.

目前只会在获取key的时候检查key是否过期然后删除，即惰性删除。这样会导致内存的浪费。可以实现一种机制，根据内存占用率自动清除过期数据。实现方式是：维护一个zset，score是ttl，key即原本的key。用ZRangeByScore()查出到目前为止过期的key进行删除。
该功能给自动merge功能提供了支持，因为该功能可以统计出key的有效比例。

**Comment by ShawnHXH** [comment]
使用 zset 实现是一种可行思路，那么 ZRangeByScore 要在何时触发呢？

可以考虑「在访问key时检查key是否过期」+「启动定时任务进行清理」两种触发方式。

**Comment by wangxuanni** [comment]
> 使用 zset 实现是一种可行思路，那么 ZRangeByScore 要在何时触发呢？
> 
> 可以考虑「在访问key时检查key是否过期」+「启动定时任务进行清理」两种触发方式。

目前「在访问key时检查key是否过期」已经有了，即惰性删除。定时去触发也是一种方案，或者可以监控内存占用率触发清除。

**Comment by elliotchenzichang** [comment]
可以参考时间轮算法：

1. https://zhuanlan.zhihu.com/p/608915243
2. https://spongecaptain.cool/post/widget/timingwheel/
