### ISSUE TITLE
PR提交规范建设

### ISSUE THREAD

**Issue by elliotchenzichang** [nutsdb/nutsdb#295]
PR暂定分为四种类型，也就是

1. [feat] 代表新增的特性或功能
2. [test] 代表补充单元测试的PR,
3. [refactor]代表对代码小范围的重构,
4. [perf]代表性能提升.
在提PR的时候要在PR最前面带有这些标签作为前缀，比如 [test] Add unit test for bpTree. 方便发版整理工作。

**Comment by xujiajun** [comment]
可以参考：https://github.com/nutsdb/nutsdb/blob/master/README-CN.md#%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE

**Comment by elliotchenzichang** [comment]
> 可以参考：https://github.com/nutsdb/nutsdb/blob/master/README-CN.md#%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE
> 
> ![image](https://user-images.githubusercontent.com/6065007/221732201-961fb077-add1-4631-8c79-bfd077d0ec46.png)
> 
> 如果要真正规范需要提交 有个hook之类检测

我觉得可以用这个，弄个hook，这样我们的发版也轻松很多
