### ISSUE TITLE
nutsdb v0.12.0 does not support 386/arm architectures

### ISSUE THREAD

**Issue by hivenet-philippe** [nutsdb/nutsdb#306]
**Describe the bug**
When building (cross-platform) using nutsdb v0.12.0, the build fails due to math.MaxUint32 introduced in https://github.com/nutsdb/nutsdb/pull/286/files -> https://github.com/elliotchenzichang/nutsdb/blob/master/tx.go#L182

**To Reproduce**
pull the 0.12.0 version
run go build targetting an ARM or 386 architecture
```
GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 go build
```
or
```
GOOS=linux GOARCH=386 CGO_ENABLED=0 go build
```
fails with
```
.\tx.go:182:29: constant 4294967295 overflows int
```

**Expected behavior**
The code still compiles for GOARC 386/ARM

**please complete the following information :**
 - OS: windows 11/ubuntu 20
 - NutsDB Version 0.12.0

**Additional context**
Should be fixable by either replacing 
```
if len(entry.Meta.Bucket) >= math.MaxUint32 || len(entry.Key) >= math.MaxUint32 || len(entry.Value) >= math.MaxUint32 {
  return ErrDataSizeExceed
}
```
with
```
if len(entry.Meta.Bucket) >= math.MaxInt32|| len(entry.Key) >= math.MaxInt32|| len(entry.Value) >= math.MaxInt32{
  return ErrDataSizeExceed
}
```

side-effect -> reduces to max size from 4294967295 to 2147483647

Or by introducing a const.go file with build directive for 386/arm or not

Happy to do a PR for any of those, as this is blocking my project ;)

**Comment by guillaumerenault** [comment]
Upvoting this issue as it's a blocker for my project as well!

**Comment by xujiajun** [comment]
@hivenet-philippe ok. please give me a PR to fix it

**Comment by elliotchenzichang** [comment]
Seems we already fixed it. So I closed this issue.
