### ISSUE TITLE
Error or not an error deleting a nonexistent key

### ISSUE THREAD

**Issue by waldirborbajr** [nutsdb/nutsdb#317]
**Describe the bug**

I'm trying to send an error to the user when trying to delete a nonexistent key, but no error is raised.

**To Reproduce**

I've made a branch adding some println as debug to track what it is happening.

https://github.com/waldirborbajr/kvstok/blob/issue/cmd/commands/del.go

Step 01 - Add some keys
-------------------------
go run cmd/cli/main.go a test1 test0101
go run cmd/cli/main.go a test2 test2222

Step 02 - List added keys
-------------------------
go run cmd/cli/main.go l
test1   test0101
test2   test2222

Step 03 - Deleting test1 - WORKING
-----------------------------------
go run cmd/cli/main.go d test1
DONE deleted

Step 04 - Verifying - WORKING
-----------------------------
go run cmd/cli/main.go l
test2   test2222

**NOW DELETE SAME KEY AGAIN** 
**************************

Step 05 - Deleting the same key -> Should raise an error because the key does not exist
--------------------------------------------------------------------------------
go run cmd/cli/main.go d test1
DONE deleted

**Expected behavior**

Should raise an error because key [test1] does not exist anymore because was removed previously.

**What actually happens**

No error it is raise, and application exit as success on delete a non-existent key.

**Screenshots**
n/a

**please complete the following information :**
 - OS: [e.g. Pop-OS]
 - NutsDB Version [e.g. 1.12.0]

**Additional context**
n/a

**Comment by waldirborbajr** [comment]
Hi,

Do you reproduce the problem that I'm facing here, about deleting a non-existent record?

**Comment by elliotchenzichang** [comment]
@waldirborbajr hi， Sorry for being late. I will take this issue for now.

**Comment by elliotchenzichang** [comment]
@waldirborbajr Hi, this is a bug after I read the code, and I raised a PR to fix it. Will release a tiny version this weekend. Thank you for raising this issue. And the PR is #331

**Comment by waldirborbajr** [comment]
@elliotchenzichang thank you so much for your attention.

**Comment by elliotchenzichang** [comment]
hi @waldirborbajr, v0.12.1 has been released. Now I closed this issue, Thanks for your contribution.
