### ISSUE TITLE
tx.db.committedTxIds会包含错误的事务id吗

### ISSUE THREAD

**Issue by ybnx** [nutsdb/nutsdb#318]
如果entry写入文件出错，tx.db.committedTxIds会包含错误的事务id吗，我在Rollback函数里面也没看到回滚committedTxIds的操作

**Comment by elliotchenzichang** [comment]
hi, @ybnx ，不会的，因为committedTxIds是事务中所有数据都写入成功后才更新的，如果其中一条数据写入数据出错，是不会更新这个committedTxIds的。所以在rollback的时候也不需要操作这个字段。

**Comment by elliotchenzichang** [comment]
但是在排查这个问题看代码的时候发现我们关于在tx上的状态上有并发安全问题。已提交MR修复，感谢。

**Comment by elliotchenzichang** [comment]
总结了一篇文章，感兴趣可以看看，https://mp.weixin.qq.com/s/oIx2VZO3IMakh1DuT5p9jg。 这个issue我先关了
