### ISSUE TITLE
Set all fields in db to nil and add an optional config to determine whether we should manually call runtime.GC() in the close() method

### ISSUE THREAD

**Issue by elliotchenzichang** [nutsdb/nutsdb#352]
We noticed that it's not every reference relationship in the db instance will cut down when the user calls the close() method, so if we want to release memory after calling the close method. So that's an optimal approach to cut down all the reference relationships of the fields in the db instance and add an optional config in the Options object to determine whether it should call runtime.GC() to release memory immediately.

我们发现在调用close方法的时候并不是所有字段对象的引用都会在close方法中断掉，这个时候有一些内存实际上不能被马上清楚掉，所以这里提供了一个优化的机会，也就是在close方法中把db中所有字段都设置成nil，并且可以添加一个配置选项，在close方法的最后手动调用一次runtime.GC() 可以帮助立马释放掉内存。由于手动GC会带来一些性能损耗，比如程序停顿，所以这是一个选项，开这个口子给用户选择。

**Comment by elliotchenzichang** [comment]
@infdahai Hi, this task has been taken a few minutes ago in this issue #347, would you like to take another interesting task? thanks.

**Comment by infdahai** [comment]
Ok, I see that.

**Comment by elliotchenzichang** [comment]
was fix by this PR. https://github.com/nutsdb/nutsdb/pull/374
