### ISSUE TITLE
tx.DeleteBucket()方法未正确生效

### ISSUE THREAD

**Issue by zhujing3** [nutsdb/nutsdb#386]
**Describe the bug**
tx.delete()方法实际未删除指定bucket

**To Reproduce**
这个测试程序执行两次删除都未有报错
```go
func DelBucket() {
	start := time.Now()
	dbf := "/tmp/nutsdb01_v2"

	db, _ := nutsdb.Open(nutsdb.DefaultOptions, nutsdb.WithDir(dbf), nutsdb.WithEntryIdxMode(nutsdb.HintKeyAndRAMIdxMode))
	tx, _ := db.Begin(true)
	if err := tx.DeleteBucket(nutsdb.DataStructureSet, "full"); err != nil {
		fmt.Println("del bucket error", err)
	}
	if err := tx.Commit(); err != nil {
		panic(err)
	}
	// if err := db.Merge(); err != nil {
	// 	panic(err)
	// }
	db.Close()
	fmt.Printf("time.Since(start): %v\n", time.Since(start))

}

func main() {
	DelBucket()
	DelBucket()
}
```
版本 0.12.6

<img width="666" alt="23423994c4d96d13d76abb7f1304647" src="https://github.com/nutsdb/nutsdb/assets/11979531/1d21d5a6-a92e-49a0-9ce4-c8034e13eea8">

<img width="586" alt="2f4fc7a9caefdcda98b63caceeb41d9" src="https://github.com/nutsdb/nutsdb/assets/11979531/87b819c4-959d-42b6-8914-82cb293d4c64">

**Comment by xujiajun** [comment]
应该是没有判断这个bucket是否存在，有没有小伙伴帮解决下。。

**Comment by bigboss2063** [comment]
I fix this in pr #388.

**Comment by elliotchenzichang** [comment]
已经由 @bigboss2063 修复。代码合进去了，等待下一个版本发布。
