### ISSUE TITLE
enhance: The Begin method can be used for memory optimization

### ISSUE THREAD

**Issue by tobehardest** [nutsdb/nutsdb#394]
<img width="756" alt="image" src="https://github.com/nutsdb/nutsdb/assets/88612778/d194995e-f1ff-4c9e-91b2-617b846937af">
<img width="730" alt="image" src="https://github.com/nutsdb/nutsdb/assets/88612778/cd5f5a03-2201-44e4-aac1-0591ffabf82d">

The Begin method needs to create a new Tx object every time, and most APIs rely on the Begin method to create a large number of Tx objects, so you can use sync.Pool for reuse optimization. At the same time, the newTx method does not need to initialize pendingWrites and ReservedStoreTxIDIdIdxes in read-only mode, which can also be optimized for memory.

**Comment by elliotchenzichang** [comment]
Tx will still be handled by the user.  So cache it will cause a bug.
