### ISSUE TITLE
整理readme 文件

### ISSUE THREAD

**Issue by elliotchenzichang** [nutsdb/nutsdb#402]
现在我们的readme文件太长了，可以采用一些办法整理一下。
目前大部分内容都是API操作相关。
<img width="1012" alt="image" src="https://github.com/nutsdb/nutsdb/assets/92676541/9dd7efc9-ed56-42b9-ae4d-25fc53486e83">
我最近看到
https://github.com/milvus-io/milvus 向量数据库的readme，其实一些内容是可以通过markdown语法折叠起来的。希望有人可以帮忙按照这个格式整理折叠一下对应数据结构的API操作。
google搜索了一下折叠内容的markdown语法，可以参考这里。
https://keatonlao.gitee.io/a-study-note-for-markdown/syntax/%E8%AF%A6%E7%BB%86%E7%89%88/markdown-%E6%8A%98%E5%8F%A0%E5%86%85%E5%AE%B9/

**Comment by xujiajun** [comment]
建议对应的数据结构 对应的拆开维护，方便对单个精细化编写，如编写set，能描述清楚功能、实例、时间复杂度、注意事项、最佳实践等。

**Comment by elliotchenzichang** [comment]
> 建议对应的数据结构 对应的拆开维护，方便对单个精细化编写，如编写set，能描述清楚功能、实例、时间复杂度、注意事项、最佳实践等。

是的，这样更好，可以把对应数据结构拆成到别的地方去，readme引用即可。

**Comment by hanxuanliang** [comment]
Can be assigned to me, give it a try.

**Comment by elliotchenzichang** [comment]
@hanxuanliang Thanks! Assigned this issue to you in next release plan. #403
