### ISSUE TITLE
统计一下用户的Golang版本

### ISSUE THREAD

**Issue by elliotchenzichang** [nutsdb/nutsdb#408]
当前我们在做一些代码重构的工作，不知道要兼容golang到哪个版本。这样做的好处是用到一些新的feature的时候需不需要照顾到这个feature出来之前的golang版本。比如范型。

**Comment by bigboss2063** [comment]
现在项目 go.mod 中的版本号是 go1.13，跟目前的版本已经差距比较远

**Comment by pangbit** [comment]
1.20.4
