### ISSUE TITLE
HintBPTSparseIdxMode模式下支持Merge操作

### ISSUE THREAD

**Issue by barryzxy** [nutsdb/nutsdb#413]
我在嵌入式中测试,嵌入是设备内存比较小512m内存, 在另外两种模式下启动时间比较久,内存占用比较高, 在HintBPTSparseIdxMode下启动时间内存占用都比较好.

**Comment by elliotchenzichang** [comment]
我们将会删除第三种模式，改用leveldb支持一些场景，所以这个issue我认为应该不用做了。
