### ISSUE TITLE
db.buildIndexes error: when build SetIdx SRem index err: key not found

### ISSUE THREAD

**Issue by lovefy-eth** [nutsdb/nutsdb#431]
**Describe the bug**
这个错误是什么原因？我正在改写我的项目用nutsdb，但是重启的时候数据库好像坏了？这跟我强制关闭软件有关系吗？但是我已经开启SyncEnable了

**Comment by lovefy-eth** [comment]
大概知道原因了，应该是我的key用的是byte类型，而且都是空字节，我不明白为什么接口中好多key又变成string类型了

**Comment by lovefy-eth** [comment]
好像是我删除一个不存在的Set KEY，然后重启的时候会找不到这个KEY报错？

**Comment by lovefy-eth** [comment]
确实是这个原因，希望能修复一下！还有，key 既然是[]byte类型，为什么还有很多地方用的是string类型

**Comment by bigboss2063** [comment]
> 确实是这个原因，希望能修复一下！还有，key 既然是[]byte类型，为什么还有很多地方用的是string类型

正在修复中

**Comment by bigboss2063** [comment]
你好，之前的版本无论 bucket 是否存在、set 是否存在、member 是否存在都允许执行 SRem，现在已经修复，只有前三个条件都存在的情况下才允许执行 SRem。

根据你的建议，我将事务的接口中 key 都统一成了 []byte 的类型。

修复发布在预发布版本 v0.13.1 中，请更新一下并测试。

感谢你提出的issue！ @lovefy-eth
