### ISSUE TITLE
It's should return ErrListNotFound when calling tx.LRemByIndex with a non-existent bucket name

### ISSUE THREAD

**Issue by TremblingV5** [nutsdb/nutsdb#469]
**Describe the bug**
In unit test cases, there's a case is calling `tx.LRemByIndex` with a non-existent bucket name. And it returns `nil`.
I think it should be consistent with `tx.LRem` which returning  `ErrListNotFound` when called with a non-existent bucket name.

**To Reproduce**
Run test case `txLRemByIndex`

**please complete the following information :**
 - OS: Ubuntu 22.04
 - NutsDB Version: the newest of master

**Comment by bigboss2063** [comment]
Can you open a PR to help fix it? Thanks!

**Comment by TremblingV5** [comment]
> Can you open a PR to help fix it? Thanks!

OK 👌
