### ISSUE TITLE
[peformance] 优化测试用例速度

### ISSUE THREAD

**Issue by elliotchenzichang** [nutsdb/nutsdb#486]
发现本地跑测试用例特别慢，主要集中在这两个case上面。

1. TestBatchWrite
2. TestIsPrefixScan

有时间可以看下这两个case，优化一下速度。
有一个case一直在转圈圈，怀疑有死锁。

1. TestTx_Rollback

**Comment by bigboss2063** [comment]
TestTx_Rollback 本地会转圈吗，还是跑 workflow 的时候转圈

**Comment by elliotchenzichang** [comment]
> TestTx_Rollback 本地会转圈吗，还是跑 workflow 的时候转圈

会的，我在本地跑的时候会一直转圈

**Comment by bigboss2063** [comment]
> > TestTx_Rollback 本地会转圈吗，还是跑 workflow 的时候转圈
> 
> 会的，我在本地跑的时候会一直转圈

我本地测试了没出现这个问题

**Comment by elliotchenzichang** [comment]
> > > TestTx_Rollback 本地会转圈吗，还是跑 workflow 的时候转圈
> > 
> > 
> > 会的，我在本地跑的时候会一直转圈
> 
> 我本地测试了没出现这个问题

看了一下，是改动的代码有问题，修复了
