### ISSUE TITLE
new version compatiable for old version data (新版本对于老版本数据的兼容性问题)

### ISSUE THREAD

**Issue by xiongguangjie** [nutsdb/nutsdb#489]
i update v0.12.x to v0.14.2 , i found v0.14.2 not compatiable   data of v0.12.x
======================================================
我从v0.12.x 更新到v014.2 ,发现v0.14.2 不兼容v0.12.x的数据

**Comment by elliotchenzichang** [comment]
Hi 你启动的时候会报什么错吗？可以贴一下错误吗

**Comment by xiongguangjie** [comment]
> Hi 你启动的时候会报什么错吗？可以贴一下错误吗

数据不正确，有很多异常数据

**Comment by xiongguangjie** [comment]
更新时，我做了merge 操作，以前是没有的

**Comment by bigboss2063** [comment]
请问使用的是哪种数据结构 @xiongguangjie

**Comment by xiongguangjie** [comment]
> 请问使用的是哪种数据结构 @xiongguangjie

默认的

**Comment by xiongguangjie** [comment]
是set 之类的数据结构吧，我是 kv与set

**Comment by xiongguangjie** [comment]
我有很多的bucket ,我会遍历所有bucket,但是我更新后，发现很多有很多不存在的bucket ,我回退后就正常了

**Comment by bigboss2063** [comment]
这些不存在的 bucket 是本来应该删掉的但是还在还是凭空出现的 bucket？可以帮忙从 v0.14.1 往回测试一下吗？

**Comment by xiongguangjie** [comment]
> 这些不存在的 bucket 是本来应该删掉的但是还在还是凭空出现的 bucket？可以帮忙从 v0.14.1 往回测试一下吗？

等一下我把上传下数据，你可以很容易复现

**Comment by bigboss2063** [comment]
> > 这些不存在的 bucket 是本来应该删掉的但是还在还是凭空出现的 bucket？可以帮忙从 v0.14.1 往回测试一下吗？
> 
> 等一下我把上传下数据，你可以很容易复现

好的，方便上传数据的话也可以

**Comment by xiongguangjie** [comment]
数据：
[data.tar.gz](https://github.com/nutsdb/nutsdb/files/13423943/data.tar.gz)
新版本异常遍历的bucket
![异常遍历的bucket](https://github.com/nutsdb/nutsdb/assets/19631632/b2e4f1c6-eb33-4040-8784-1d70da352a23)
老版本正常遍历的bucket
![正常遍历的bucket](https://github.com/nutsdb/nutsdb/assets/19631632/7f72d9d4-9e93-4738-a556-c2ba589ac5b9)

**Comment by bigboss2063** [comment]
方便的话麻烦把代码一并贴一下

**Comment by xiongguangjie** [comment]
> 方便的话麻烦把代码一并贴一下
![代码片段](https://github.com/nutsdb/nutsdb/assets/19631632/74bffee3-39b7-4c1f-b898-d80acbf444fe)

**Comment by bigboss2063** [comment]
已经定位到问题，将尽快修复

**Comment by bigboss2063** [comment]
已经在 0.14.3 版本中修复 @xiongguangjie

**Comment by xiongguangjie** [comment]
> 已经在 0.14.3 版本中修复 @xiongguangjie

简单测试了下，没有问题
