### ISSUE TITLE
`managed` func returns an error that cannot be tested against standard nutsdb errors e.g. `ErrBucketEmpty`

### ISSUE THREAD

**Issue by xy3** [nutsdb/nutsdb#492]
**Describe the bug**

Since this commit: https://github.com/nutsdb/nutsdb/commit/ae5e45adc76ca515f54221aa6ebe6c2b6af21823 it is now very difficult to check which error is being caused inside a managed transaction.

My code broke after updating nutsdb. Previously I could check if the managed transaction resulted in a `nutsdb.ErrBucketEmpty` and handle it gracefully. Now I cannot.

**To Reproduce**

Try to run this with an empty bucket:

```go
func main() {
	// ...

	err := db.View(func(tx *nutsdb.Tx) error {
		_, err := tx.GetAll("empty_bucket")
		return err
	})

	if errors.Is(err, nutsdb.ErrBucketEmpty) {
		// success - expected outcome
		fmt.Println("success")
	} else {
		// fail - unexpected outcome (this is the case that is occurring)
		panic(err)
	}
}
```

**Expected behavior**

[managed func (db.go#L873)](https://github.com/nutsdb/nutsdb/blob/c1b21f5540663824d9bb9e4daecc30a021873325/db.go#L873) should return the result of `fn(tx)`

**What actually happens**

[managed func (db.go#L894)](https://github.com/nutsdb/nutsdb/blob/c1b21f5540663824d9bb9e4daecc30a021873325/db.go#L894) returns a dynamically formatted error: `fmt.Errorf("%v. Rollback err: %v", err, errRollback)`

**Screenshots**

![image](https://github.com/nutsdb/nutsdb/assets/32339757/903e346f-8ed1-4e16-b704-33f14dbcac29)

**please complete the following information :**
 - OS: Ubuntu 22.04.3 LTS
 - NutsDB Version: v0.14.3

**Comment by bigboss2063** [comment]
This is a very good suggestion. Thanks!
