### ISSUE TITLE
tx.NewBucket() must be called with tx.SubmitBucket()

### ISSUE THREAD

**Issue by runningmaster** [nutsdb/nutsdb#523]
`v1.0.1`

This [code](https://github.com/nutsdb/nutsdb/blob/master/docs/user_guides/use-buckets.md) doesn't work (`bucket is not exist yet, please use NewBucket function to create this bucket first`)
```go
	key := []byte("key001")
	val := []byte("val001")
	
	bucket001 := "bucket001"
	if err := db.Update(
		func(tx *nutsdb.Tx) error {
			// you should call Bucket with data structure and the name of bucket first 
			tx.NewBucket(DataStructureBTree, bucket001)
			if err := tx.Put(bucket001, key, val, 0); err != nil {
				return err
			}
			return nil
		}); err != nil {
		log.Fatal(err)
		}
```

And that's how it works (we have to call `tx.SubmitBucket()`):
```go
	key := []byte("key001")
	val := []byte("val001")
	
	bucket001 := "bucket001"
	if err := db.Update(
		func(tx *nutsdb.Tx) error {
			// you should call Bucket with data structure and the name of bucket first 
			tx.NewBucket(DataStructureBTree, bucket001)
			tx.SubmitBucket() // <-- (!!!)
			if err := tx.Put(bucket001, key, val, 0); err != nil {
				return err
			}
			return nil
		}); err != nil {
		log.Fatal(err)
		}
```

**Comment by bigboss2063** [comment]
Thank you for your reminder. 

There is a problem with the user documentation. Currently, operations of Bucket in a Tx are not visible. We will later implement visibility of Bucket operations within a Tx.

So now you need to start the Tx and create a Bucket, and then perform the operation after committing it.

**Comment by bigboss2063** [comment]
fixed
