### ISSUE TITLE
[Bug] Reading newly created bucket(after commit) will return `Bucket not found`

### ISSUE THREAD

**Issue by ksankeerth** [nutsdb/nutsdb#526]
**Describe the bug**
If We create a bucket and try to read it immediately (Get), We'll get errors that the bucket is not found. I analysed and debugged the code and found that, We only build indexes when committing if there are some pendingWrites only.  Therefore, We won't build tx.db.buildBTreeIdx after bucket creation. 

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
1. The below can reproduce this bug easily.

Give sample code if you can.
```go
package main

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/nutsdb/nutsdb"
)

var (
	db     *nutsdb.DB
	bucket string
)

func init() {
	fileDir := "/tmp/nutsdb_example"

	files, _ := ioutil.ReadDir(fileDir)
	for _, f := range files {
		name := f.Name()
		if name != "" {
			fmt.Println(fileDir + "/" + name)
			err := os.RemoveAll(fileDir + "/" + name)
			if err != nil {
				panic(err)
			}
		}
	}
	db, _ = nutsdb.Open(
		nutsdb.DefaultOptions,
		nutsdb.WithDir(fileDir),
		nutsdb.WithSegmentSize(1024*1024), // 1MB
	)
	bucket = "bucketForString"
}

func main() {
	err := db.Update(func(tx *nutsdb.Tx) error {
		err := tx.NewBucket(nutsdb.DataStructureBTree, bucket)
		return err
	})
	if err != nil {
		fmt.Println("Errror in creating bucket")
		return
	}
	err = db.View(func(tx *nutsdb.Tx) error {
		// tx.db.Index.bTree.exist(bucketId) this check will fail 
		_, err := tx.Get(bucket, []byte("key"))
		return err
	})
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

**Expected behavior**
We should not get `Bucket Not found " errors after creating bucket successfully. After creating a bucket, We may have to build indexes.

**What actually happens**
A clear and concise description of what actually happens.

https://github.com/nutsdb/nutsdb/blob/master/tx.go#L277 Here, We only build indexes after pending writes. So If We create a bucket and insert some entries into it, We won't get this error.

**Screenshots**

**please complete the following information :**
 - OS:  Mac OS
 - NutsDB Version 1.0.1

**Additional context**

**Comment by ksankeerth** [comment]
Hi Team,

It seems to be a bug. I'll try to send a PR to fix it. I need this fix to complete #517  (I noticed this bug when my tests were failing). 

Thanks,
Sankeerthan

**Comment by bigboss2063** [comment]
Hi ksankeerth, thanks for your issue. For now, operations of a Bucket are designed not to be visible within the same Tx. We will solve this problem later.

For your tests, you can refer to the tests in db_test.go to create a Bucket and do tests.

https://github.com/nutsdb/nutsdb/blob/727ec20a08fb68743c75e563e07a866fe9c3dab0/db_test.go#L158.

**Comment by bigboss2063** [comment]
I see.
