### ISSUE TITLE
[BUG] must be ignore error bucket not exist

### ISSUE THREAD

**Issue by yudhasubki** [nutsdb/nutsdb#532]
**Describe the bug**
If we create and delete a bucket and try to reopen there will get an error 
`db.buildIndexes error: bucket not exist`

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
1.   Create, Delete, and Reopen the DB

Give sample code if you can.

```
func TestDB_ReopenWithDelete(t *testing.T) {
	var opts *Options
	if opts == nil {
		opts = &DefaultOptions
	}
	if opts.Dir == "" {
		opts.Dir = NutsDBTestDirPath
	}
	db, err := Open(*opts)
	require.NoError(t, err)
	defer removeDir(opts.Dir)

	bucket := "bucket"
	txCreateBucket(t, db, DataStructureList, bucket, nil)
	txPush(t, db, bucket, []byte("try"), []byte("1"), true, nil, nil)
	txPush(t, db, bucket, []byte("try"), []byte("2"), true, nil, nil)
	txDeleteBucket(t, db, DataStructureList, bucket, nil)

	if !db.IsClose() {
		require.NoError(t, db.Close())
	}

	db, err = Open(*opts)
	require.NoError(t, err)
	txCreateBucket(t, db, DataStructureList, bucket, nil)
	txDeleteBucket(t, db, DataStructureList, bucket, nil)
	if !db.IsClose() {
		require.NoError(t, db.Close())
	}
}
```

**Expected behavior**
Must be don't show an error `buildIdexes`

**What actually happens**
A clear and concise description of what actually happens.

**Screenshots**

**please complete the following information :**
- OS: Mac OS
- NutsDB Version 1.0.1

**Additional context**

**Comment by yudhasubki** [comment]
Hi guys,

It seems a bug, I created the PR above to fix it. Could you guys check it? 

Thanks

**Comment by bigboss2063** [comment]
Thanks!
