### ISSUE TITLE
1.0.1版本在同一个事务中使用NewBucket之后，进行Put，提示Bucket不存在

### ISSUE THREAD

**Issue by diiyw** [nutsdb/nutsdb#535]
**Describe the bug**
1.0.1版本在同一个事务中使用NewBucket之后，进行Put，提示Bucket不存在

 bucket is not exist yet, please use NewBucket function to create this bucket first

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
```go
        opt := nutsdb.DefaultOptions
	opt.Dir = filepath.Join("./", "db")
	db, err := nutsdb.Open(opt)
	if err != nil {
		panic(err)
	}
	tx, err := db.Begin(true)
	if err != nil {
		panic(err)
	}
	fmt.Println(tx.NewBucket(nutsdb.DataStructureBTree, "test"))
	err = tx.Put("test", []byte("test"), []byte("test"), 0)
	if err != nil {
		panic(err)
	}
```

Panic : bucket is not exist yet, please use NewBucket function to create this bucket first
Give sample code if you can.

**Comment by bigboss2063** [comment]
目前在同一事务中对 Bucket 的操作是不可见的，后续版本会解决这个问题，现在需要先在一个事务中创建 Bucket
