### ISSUE TITLE
[BUG] error concurrent map writes

### ISSUE THREAD

**Issue by yudhasubki** [nutsdb/nutsdb#536]
**Describe the bug**
I build a message queue with NutsDB, but I always get errors when I have a goroutine to watch with LPeek. 

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
1.   you can check on my code here https://github.com/yudhasubki/blockqueue/blob/main/listener.go#L108

Give sample code if you can.

**Expected behavior**
handling concurrent map writes

**What actually happens**
panic concurrent map writes

**Screenshots**
<img width="1036" alt="Screen Shot 2023-12-11 at 19 03 53" src="https://github.com/nutsdb/nutsdb/assets/17976036/a079f04a-d94e-404d-9720-e1404a96a70d">

**please complete the following information :**
 - OS: MacOS
 - NutsDB Version 1.0.1

**Additional context**

**Comment by yudhasubki** [comment]
That sounds like a good idea @bigboss2063 , If the Read-only behavior doesn't allow us to create the index immediately I think we need another function to create the index first before using it, is that correct?

**Comment by bigboss2063** [comment]
I think we only need to modify the logic in the read operation API.

All the API(what ever read or write) we just use `exist` to check and get the index. We **only** create a new index when a bucket was created(this part was implemented).

**Comment by bigboss2063** [comment]
Do you want to do this fix?😁

**Comment by yudhasubki** [comment]
No worries, let me fix it @bigboss2063 😄

**Comment by bigboss2063** [comment]
> No worries, let me fix it @bigboss2063 😄

Thanks!
