### ISSUE TITLE
是否可以支持iterator?

### ISSUE THREAD

**Issue by jiadexin** [nutsdb/nutsdb#54]
**支持iterator**
Iterator应该是范围扫描常用的方式，我们使用GO+CGO+RocksDB构建应用，就大量使用到Iterator。

**希望支持iterator**
nutsdb是个原生GO语言kv数据库，希望能增加正向iterator和反向iterator的功能，我们就可以拿来试用替换rocksdb，再也不用CGO了:)

**Comment by xujiajun** [comment]
@jiadexin 好的。可以支持。

**Comment by xujiajun** [comment]
更新进度：
目前v0.11.0 支持正向和反向迭代。
支持EntryIdxMode: HintKeyAndRAMIdxMode 、 HintKeyValAndRAMIdxMode 。
剩下 HintBPTSparseIdxMode 暂时还不支持。
