### ISSUE TITLE
服务器在数据读写过程中异常断电，是否有概率出现crc error？

### ISSUE THREAD

**Issue by k359792067** [nutsdb/nutsdb#569]
我的场景是在嵌入式应用中，用于存储一些设备的当前状态信息，数据量不大会定时读写（大概每5秒一次，相同的key基本是单个协程读写），猜测可能是在数据库读写过程中断电，重新开机后出现crc error，目前只能删掉数据文件恢复，想知道有没有什么办法能定位问题原因以及是否有恢复办法。
版本：github.com/nutsdb/nutsdb v1.0.1
运行环境：GOOS=linux GOARCH=arm64 Ubuntu 20.04.6 LTS
初始化代码：
```
const (
	defaultKVBucket   = "__default_kv_bucket"
	defaultListBucket = "__default_list_bucket"
)

type nutsDB struct {
	db *nutsdb.DB
}

func NewNutsDB(dir string) *nutsDB {
	db, err := nutsdb.Open(
		nutsdb.DefaultOptions,
		nutsdb.WithDir(dir), // 数据库会自动创建这个目录文件
	)
	if err != nil {
		if err == nutsdb.ErrCrc {
			fmt.Printf("nutsdb crc error, please check %s and restart\n", dir)
		}
		panic(err)
	}

	// init default bucket
	if err := db.Update(
		func(tx *nutsdb.Tx) error {
			e1 := tx.NewBucket(nutsdb.DataStructureBTree, defaultKVBucket)
			if e1 != nil && e1 != nutsdb.ErrBucketAlreadyExist {
				return err
			}

			e2 := tx.NewBucket(nutsdb.DataStructureList, defaultListBucket)
			if e2 != nil && e2 != nutsdb.ErrBucketAlreadyExist {
				return err
			}
			return nil
		}); err != nil {
		utils.Logger(context.TODO()).WithError(err).Errorf("init default bucket failed, err: %v", err)
	}

	return &nutsDB{db: db}
}
```

**Comment by bigboss2063** [comment]
你好，请问 crc 校验失败是出现了一次还是经常复现？异常断电可能没写完是有概率数据会出问题。

**Comment by k359792067** [comment]
> 你好，请问 crc 校验失败是出现了一次还是经常复现？异常断电可能没写完是有概率数据会出问题。

12月到目前为止出现了2次

**Comment by TremblingV5** [comment]
如果方便的话，我想确认下：

- 一般读写数据的k/v长度大概在多少
- 读写数据的k/v内容大概是什么样的
- 12月以来异常断电的频率是多少

**Comment by k359792067** [comment]
> 如果方便的话，我想确认下：
> 
> * 一般读写数据的k/v长度大概在多少
> * 读写数据的k/v内容大概是什么样的
> * 12月以来异常断电的频率是多少

key一般是50个字节左右，value一般在100~200个字节，value内容主要分两种json数据和protobuf数据。
pb数据写频率最高会到每秒2次，大多数key的读写频率在5秒左右。
3块开发板每天都是直接关电源，目前只出现过两次crc error，并且不在同一台设备上

**Comment by bigboss2063** [comment]
根据描述应该就是断电导致数据写入有问题了，如果可以的话可以先调用 Close 再断电。
