### ISSUE TITLE
The GetAll function only return values not contians keys

### ISSUE THREAD

**Issue by WangNingkai** [nutsdb/nutsdb#572]
https://github.com/nutsdb/nutsdb/blob/4b73679cf1a7b5471f32a0105683833794569cbe/tx_btree.go#L177

**Comment by bigboss2063** [comment]
Hi, if you need to get all keys, we could provide  APIs named `GetKeys` and `GetValues`.And modify `GetAll` back to return all keys and values. I think this is more reasonable?

**Comment by bigboss2063** [comment]
Now you can ues it in the latest version.
