### ISSUE TITLE
pref: pre-computed to reduce the overhead of computing the crc of the flags of entry.

### ISSUE THREAD

**Issue by bigboss2063** [nutsdb/nutsdb#579]
Because the crc of  flags like `DataFlag, DataStatus and DataStructure` is definite，We could pre-computed to reduce the overhead of computing the crc like LevelDB.

**Comment by ksankeerth** [comment]
Hi @bigboss2063,

Can I work on it?

Thanks,
Sankeerthan

**Comment by bigboss2063** [comment]
> Hi @bigboss2063,
> 
> Can I work on it?
> 
> Thanks, Sankeerthan

Of course, but the feasibility of this plan still needs to be considered, we can discuss it

**Comment by ksankeerth** [comment]
Hi @bigboss2063 ,

I went through the code. I see the below is the encoding format for the entry.

<img width="1010" alt="image" src="https://github.com/nutsdb/nutsdb/assets/33720251/90fddd09-38d1-415a-8a85-b6713a341a15">

Between `Ds` and `flag` bytes, there are some other bytes `TTL` and `status`. Therefore, I believe We cannot use pre-Computed CRCs for `Ds` and `flags` with the current encoding format.  (btw, I'm not an expert in CRCs. )

**Comment by bigboss2063** [comment]
Whether we can do it in a reasonable order when constructing the CRC does not seem to have an impact? The underlying storage is stored as it is, and in the order we need when constructing the CRC.
