### ISSUE TITLE
nil pointer dereference panic

### ISSUE THREAD

**Issue by jxsl13** [nutsdb/nutsdb#580]
**Describe the bug**
It is possible for this entry to become nil causing the library to panic.
https://github.com/nutsdb/nutsdb/blob/a4ca1b95b3d6640d87d1e0693f6464a48ace4e11/tx.go#L234

**To Reproduce**
I have a small project that I'm trying to port from Redis to nutsdb in which I encountered this bug.

Steps to reproduce the behavior(Be specific!):
If you want to reproduce it, you can run the following test:
https://github.com/jxsl13/nutbreaker/blob/e2b61438dd20400696aac7fc7fd70c760e58b6da/nutbreaker_insert_test.go#L267

**Expected behavior**
I expect the library not to panic with a nil pointer dereference.

**What actually happens**
The library panics with a nil pointer dereference.

**Screenshots**
none

**please complete the following information :**
 - OS: macOS 14.3 Sonoma
 - NutsDB Version: v1.0.3

**Additional context**

```
--- FAIL: TestInsertDoubleBoundaryInsideLB (2.47s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100b32024]

goroutine 19 [running]:
testing.tRunner.func1.2({0x100d25520, 0x100f40fa0})
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1545 +0x5d8
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1548 +0x83c
panic({0x100d25520?, 0x100f40fa0?})
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/panic.go:920 +0x254
github.com/nutsdb/nutsdb.(*Entry).Size(0x0)
	/Users/john/go/pkg/mod/github.com/nutsdb/nutsdb@v1.0.3/entry.go:48 +0x34
github.com/nutsdb/nutsdb.(*Tx).Commit(0xc000181280)
	/Users/john/go/pkg/mod/github.com/nutsdb/nutsdb@v1.0.3/tx.go:235 +0x714
github.com/jxsl13/nutbreaker.(*NutBreaker).Insert.func1()
	/Users/john/Desktop/nutbreaker/nutbreaker.go:333 +0x1f0
github.com/jxsl13/nutbreaker.(*NutBreaker).Insert(0xc00011e0a0, {0x100c5766c, 0x9}, {0xc0001d349e, 0xa, 0xa})
	/Users/john/Desktop/nutbreaker/nutbreaker.go:337 +0x33c
github.com/jxsl13/nutbreaker.insert(0xc00010b040, 0xc00011e0a0, 0x1, {0xc0001d3c78, 0x2, 0x2})
	/Users/john/Desktop/nutbreaker/nutbreaker_helpers_test.go:70 +0x8f0
github.com/jxsl13/nutbreaker.TestInsertDoubleBoundaryInsideLB(0xc00010b040)
	/Users/john/Desktop/nutbreaker/nutbreaker_insert_test.go:271 +0x184
testing.tRunner(0xc00010b040, 0x100d72e58)
```

**Comment by TremblingV5** [comment]
Thanks for your issue, and I can reproduce it (although I only have a ubuntu).

I also think it should not be panic. I think it could be ignored when an entry is nil. I will confirm the plan for improving this issue with other senior contributors.

Of course, welcome leaving more comments or more contributions if you want to fix this bug or have more advices.

**Comment by waldirborbajr** [comment]
I'm facing the same issue when Open a database.

	database, err = nutsdb.Open(
		nutsdb.DefaultOptions,
		nutsdb.WithDir(homePath),
		nutsdb.WithSegmentSize(DBSIZE),
	)
	if err != nil {
		log.Fatal(err)
	}

Error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x61a8b0]

**Comment by bigboss2063** [comment]
Please have a try when update to the latest version.
