### ISSUE TITLE
Capability to list all buckets

### ISSUE THREAD

**Issue by arwer13** [nutsdb/nutsdb#65]
Hello! I'm trying to write a console viewer for your database. I wander is there a way to list all buckets?
It looks like I should just iterate keys of `db.BPTreeIdx` is it the right way?

**Comment by xujiajun** [comment]
@arwer13 

The current version does not yet support access to all bucket APIs. Later versions will support this feature.

**Comment by uded** [comment]
When we can expect bucket listing? Sounds like an extremely handy method...
