### ISSUE TITLE
get all keys / get higest key

### ISSUE THREAD

**Issue by marcelloh** [nutsdb/nutsdb#73]
I want to have a key that is a numeric key, so what I do now it. read all keys, get the latest value, add 1 to that, and I have my next record key.

This would probably be faster, if I could only get all keys or even better, get the highest one.

**Comment by marcelloh** [comment]
I saw there is something in BPTree > LastKey
Perhaps this is usable?

**Comment by marcelloh** [comment]
Just an experiment (not sure if it is all ok)
```
func (tx *Tx) GetLastKey(bucket string) (lastKey []byte, err error) {
	if err := tx.checkTxIsClosed(); err != nil {
		return lastKey, err
	}

	idxMode := tx.db.opt.EntryIdxMode

	if idxMode == HintKeyValAndRAMIdxMode || idxMode == HintKeyAndRAMIdxMode {
		if index, ok := tx.db.BPTreeIdx[bucket]; ok {
			lastKey = index.LastKey
		}
	}

	if len(lastKey) == 0 {
		return lastKey, ErrBucketEmpty
	}

	return lastKey, nil
}

```

**Comment by marcelloh** [comment]
this is not the correct solution (i found out) because when I delete the highest key, it will still be the last key somehow :-(

**Comment by bigboss2063** [comment]
Add GetMaxKey and GetMinKey for kv type #514

**Comment by marcelloh** [comment]
Thanks :-)

**Comment by bigboss2063** [comment]
> Thanks :-)

Hi, Are you still using nutsdb? 😁

**Comment by marcelloh** [comment]
Yes. Amonst others as well, I can easy switch without any problems.

Op do 30 nov 2023 om 11:57 schreef Bruce Chen ***@***.***>:
