### ISSUE TITLE
无法判断key是否存在

### ISSUE THREAD

**Issue by nightmeng** [nutsdb/nutsdb#79]
标题有些冒昧，请见谅~~~
最近有嵌入式数据库的需求，故而找到了nutsdb，了解下来觉得nutsdb的设计还是非常好的，实现常用的数据结构，可以大幅度提高开发效率，但是nutsdb的接口定义感觉存在不够完美

使用SHasKey查询Key是否存在的时候，如果bucket不存在会返回报错，但nutsdb没有单独提供bucket操作的接口

如何实现SetNX逻辑？

**Comment by xujiajun** [comment]
@nightmeng ，谢谢提出建议意见。

你的目的是 使用SHasKey查询Key是否存在，但是无法确定bucket是否存在，没有类似HasBucket 来先判断bucket 是否存在？是不是提供类似这个就好了呢？

**Comment by allanpk716** [comment]
刚接触这个项目，List 数据结构对我的项目很有帮助。也遇到类似问题。需要判断 bucket 是否存在，然后再到 key 是否存在，不存在都是直接返回 err ，不太好用。期望不是严重的故障问题，直接给一个 bool 返回值，比如，get 具体 key 的value 的时候，key ( or  bucket )不存在多给一个返回值  bool, value ,err ，如果 err 是 nil ，我们就可以直接由 bool 判断是否存在，不存在就可以更容易去写后续的插入逻辑。

**Comment by allanpk716** [comment]
或者说能够把文档写详细写，着重描述查询情况下，不存在 bucket 和 key 的时候一定返回什么 err 也行。虽然也能去看代码，但是还是期望能够完善这个部分。

**Comment by xujiajun** [comment]
> 或者说能够把文档写详细写，着重描述查询情况下，不存在 bucket 和 key 的时候一定返回什么 err 也行。虽然也能去看代码，但是还是期望能够完善这个部分。

嗯现在 你说的list 不存在bucket是返回 ErrBucket。暂时来看完善文档解决，不然这个bool设计会有奇怪

**Comment by xujiajun** [comment]
目前有对error，判断是否是key不存在，还是bucket不存在的错误做了包装和区分：
https://github.com/nutsdb/nutsdb/blob/master/errors.go#L11


https://github.com/nutsdb/nutsdb/blob/master/errors.go#L16

这个issue 我先关闭了， 有问题请再提交新的issue。
