### ISSUE TITLE
关于获取bucket 下所有list数组型 key列表方法

### ISSUE THREAD

**Issue by xs23933** [nutsdb/nutsdb#80]
环境：
```go
  bucket := "c_123456"
  LPush(bucket, "aabb", data)
  LPush(bucket, "aasd", data)
  LPush(bucket, "bbcf", data)
```
数据库中二进制存储结果好像是。c_123456aabb, c_123456aasd, c_123456bbcf 这样的结构

我的问题是 如何列出 c_123456 下的所有key [aabb,aasd, bbcf]
有人有我相同的问题么

利用bucket 列出
```go
获取全部的key和value
对于获取一个bucket的所有key和value，可以使用GetAll方法。

例子：

if err := db.View(
	func(tx *nutsdb.Tx) error {
		bucket := "c_123456"
		entries, err := tx.GetAll(bucket)
		if err != nil {
			return err
		}

		for _, entry := range entries {
			fmt.Println(string(entry.Key))
		}

		return nil
	}); err != nil {
	log.Println(err)
}
```
当前所有的key value 
entries, err := tx.GetAll(bucket)

2020/12/14 09:42:00 bucket is empty

是不支持 数组型获取key 么

**Comment by xujiajun** [comment]
@xs23933 你好， 目前没有支持这个特性（获取bucket 下所有list数组型 key列表），PS： tx.GetAll 是获取普通的SET、GET的

**Comment by Nailcui** [comment]
### 实现思路

#### API

- LKeys(bucket, pattern string) ([]string, err)
- SKeys(bucket, pattern string) ([]string, err)
- ZKeys(bucket, pattern string) ([]string, err)


#### desc

This series of APIs is used to find all keys matching a given pattern, similar to Redis's command: [KEYS](https://redis.io/commands/keys/)

Supported glob-style patterns:

- `*` matches all keys
- `h?llo` matches `hello`, `hallo` and `hxllo`
- `h*llo` matches `hllo` and `heeeello`
- `h[ae]llo` matches `hello` and `hallo,` but not `hillo`
- `h[^e]llo` matches `hallo`, `hbllo`, ... but not `hello`
- `h[a-b]llo` matches `hallo` and `hbllo`

**Comment by xujiajun** [comment]
close. see detail : https://github.com/nutsdb/nutsdb/pull/175
