### ISSUE TITLE
clarify error management

### ISSUE THREAD

**Issue by schmurfy** [nutsdb/nutsdb#87]
**Is your feature request related to a problem? Please describe.**
When you try to read multiple data and the request does not return any result (ex: `RangeScan`, `PrefixScan`) an error is returned

**Describe the solution you'd like**
Instead of returning an error I expected an empty result, this is much easier to manage instead of having to check errors which are not real errors or worse having to check the error message returned.

When `Get` does not match anything I can get this: "not match bucket <bucket>,<key>" or  a `ErrKeyNotFound`, in this case both should return `ErrKeyNotFound`

- for single returned value when an item is not found `ErrKeyNotFound` is perfect but should be always returned
- for multiple values (`RangeScan`, `PrefixScan`) an empty array should be returned, in those cases having no data returned is not an error, the user should decide.

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by xujiajun** [comment]
@schmurfy According to you, the GET operation also returns nil if it doesn't match any value, the user decides whether to process, yes?

I don't quite understand the sentence you mentioned:
> When Get does not match anything I can get this: "not match bucket ," or a ErrKeyNotFound, in this case both should return ErrKeyNotFound

Could you explain it for me in detail ?

**Comment by schmurfy** [comment]
I meant that in its current form `Get` can return at least two different error when the key does not exists, there should only be one.

**Comment by icb-** [comment]
I worked around this for myself by vendoring and changing https://github.com/xujiajun/nutsdb/blob/b1e2a9db7baa6f1edcf6cfb56696384460cb49f6/tx_bptree.go#L179 from `errors.New(...)` to
```go
return nil, fmt.Errorf("%w: not found bucket: %s, key: %s", ErrNotFoundKey, bucket, string(key))
```

This lets me detect the error as the key not found with `errors.Is(err, nutsdb.ErrNotFoundKey)`. This may not be the completely correct error to wrap, and is definitely not a complete solution, but is good enough for my current use.

It would be better to replace all calls to `errors.New(...)` in the code (other than the package-level `Err...` vars) with a `fmt.Errorf(...)` that wraps the correct error. Incidentally, there are some duplicate error vars that seem to be used for the same purpose, like `ErrNotFoundKey` and `ErrKeyNotFound`.

**Comment by xujiajun** [comment]
The current v0.9.0 version has error management. There are functions to judge whether the key does not exist, and there are functions to judge whether the bucket does not exist. Please check. If there are still problems, please submit a new issue, and I will close this issue.

https://github.com/nutsdb/nutsdb/blob/master/errors.go#L11

https://github.com/nutsdb/nutsdb/blob/master/errors.go#L16
