### ISSUE TITLE
A function that deletes the specified index (one or more)

### ISSUE THREAD

**Issue by xujiajun** [nutsdb/nutsdb#93]
另外希望能有一个函数可以删除指定index（一个或多个）的数据

_Originally posted by @mzz2017 in https://github.com/xujiajun/nutsdb/issues/66#issuecomment-640156463_

**Comment by Nailcui** [comment]
这个提议如果需要完善的话，我愿意来试试🙋‍♂️

**Comment by xujiajun** [comment]
@Nailcui ok，我放在v0.10.0 release proposal里面

**Comment by xujiajun** [comment]
> 这个提议如果需要完善的话，我愿意来试试🙋‍♂️

https://github.com/nutsdb/proposal/issues/3 ，你可以去这个帖子下面回复下，参与报名，这样我方便统计，还没加群的请加下群找我哈

**Comment by Nailcui** [comment]
> 这个提议如果需要完善的话，我愿意来试试🙋‍♂️

好的已回复，已加nuts&go学习交流群

**Comment by Nailcui** [comment]
好的已回复，已加nuts&go学习交流群

**Comment by xujiajun** [comment]
> 好的已回复，已加nuts&go学习交流群

好的。
